/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./client/index.html", "./client/src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      borderRadius: {
        lg: ".75rem",
        md: ".5rem",
        sm: ".25rem",
      },
      colors: {
        background: "hsl(var(--background) / <alpha-value>)",
        foreground: "hsl(var(--foreground) / <alpha-value>)",
        border: "hsl(var(--border) / <alpha-value>)",
        input: "hsl(var(--input) / <alpha-value>)",
        card: {
          DEFAULT: "hsl(var(--card) / <alpha-value>)",
          foreground: "hsl(var(--card-foreground) / <alpha-value>)",
          border: "hsl(var(--card-border) / <alpha-value>)",
        },
        popover: {
          DEFAULT: "hsl(var(--popover) / <alpha-value>)",
          foreground: "hsl(var(--popover-foreground) / <alpha-value>)",
          border: "hsl(var(--popover-border) / <alpha-value>)",
        },
        primary: {
          DEFAULT: "hsl(var(--primary) / <alpha-value>)",
          foreground: "hsl(var(--primary-foreground) / <alpha-value>)",
          border: "var(--primary-border)",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary) / <alpha-value>)",
          foreground: "hsl(var(--secondary-foreground) / <alpha-value>)",
          border: "var(--secondary-border)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted) / <alpha-value>)",
          foreground: "hsl(var(--muted-foreground) / <alpha-value>)",
          border: "var(--muted-border)",
        },
        accent: {
          DEFAULT: "hsl(var(--accent) / <alpha-value>)",
          foreground: "hsl(var(--accent-foreground) / <alpha-value>)",
          border: "var(--accent-border)",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
          border: "var(--destructive-border)",
        },
        ring: "hsl(var(--ring) / <alpha-value>)",
        chart: {
          "1": "hsl(var(--chart-1) / <alpha-value>)",
          "2": "hsl(var(--chart-2) / <alpha-value>)",
          "3": "hsl(var(--chart-3) / <alpha-value>)",
          "4": "hsl(var(--chart-4) / <alpha-value>)",
          "5": "hsl(var(--chart-5) / <alpha-value>)",
        },
        sidebar: {
          ring: "hsl(var(--sidebar-ring) / <alpha-value>)",
          DEFAULT: "hsl(var(--sidebar) / <alpha-value>)",
          foreground: "hsl(var(--sidebar-foreground) / <alpha-value>)",
          border: "hsl(var(--sidebar-border) / <alpha-value>)",
        },
        "sidebar-primary": {
          DEFAULT: "hsl(var(--sidebar-primary) / <alpha-value>)",
          foreground: "hsl(var(--sidebar-primary-foreground) / <alpha-value>)",
          border: "var(--sidebar-primary-border)",
        },
        "sidebar-accent": {
          DEFAULT: "hsl(var(--sidebar-accent) / <alpha-value>)",
          foreground: "hsl(var(--sidebar-accent-foreground) / <alpha-value>)",
          border: "var(--sidebar-accent-border)",
        },
        status: {
          online: "rgb(34 197 94)",
          away: "rgb(245 158 11)",
          busy: "rgb(239 68 68)",
          offline: "rgb(156 163 175)",
        },
        "brand-bg": "rgb(var(--brand-bg) / <alpha-value>)",
        "brand-bg-elevated": "rgb(var(--brand-bg-elevated) / <alpha-value>)",
        "brand-bg-card": "rgb(var(--brand-bg-card) / <alpha-value>)",
        "brand-bg-card-alt": "rgb(var(--brand-bg-card-alt) / <alpha-value>)",
        "brand-surface-raised": "rgb(var(--brand-surface-raised) / <alpha-value>)",
        "brand-border": "rgb(var(--brand-border) / <alpha-value>)",
        "brand-border-strong": "rgb(var(--brand-border-strong) / <alpha-value>)",
        "brand-border-subtle": "rgb(var(--brand-border-subtle) / <alpha-value>)",
        "brand-text-bright": "rgb(var(--brand-text-bright) / <alpha-value>)",
        "brand-text-muted": "rgb(var(--brand-text-muted) / <alpha-value>)",
        "brand-text-faded": "rgb(var(--brand-text-faded) / <alpha-value>)",
        "brand-text-dim": "rgb(var(--brand-text-dim) / <alpha-value>)",
        "brand-accent": "rgb(var(--brand-accent) / <alpha-value>)",
        "brand-accent-deep": "rgb(var(--brand-accent-deep) / <alpha-value>)",
        bull: "rgb(var(--signal-bull) / <alpha-value>)",
        bear: "rgb(var(--signal-bear) / <alpha-value>)",
        watch: "rgb(var(--signal-watch) / <alpha-value>)",
        "watch-short": "rgb(var(--signal-watch-short) / <alpha-value>)",
        reduce: "rgb(var(--signal-reduce) / <alpha-value>)",
        "trend-exit": "rgb(var(--signal-trend-exit) / <alpha-value>)",
        "short-add": "rgb(var(--signal-short-add) / <alpha-value>)",
        "bull-light": "rgb(var(--signal-bull-light) / <alpha-value>)",
        "bear-light": "rgb(var(--signal-bear-light) / <alpha-value>)",
        "watch-light": "rgb(var(--signal-watch-light) / <alpha-value>)",
      },
      fontFamily: {
        sans: ["var(--font-sans)"],
        serif: ["var(--font-serif)"],
        mono: ["var(--font-mono)"],
      },
      fontSize: {
        tiny: ["8px", { lineHeight: "10px" }],
        mini: ["9px", { lineHeight: "11px" }],
        micro: ["10px", { lineHeight: "12px" }],
        "2xs": ["11px", { lineHeight: "14px" }],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
};
