"""
BBTC — state-based trend follower (long-only).

Python port of `server/signals/strategies/bbtc.ts`. Indicator math is
sourced from pandas-ta (Wilder smoothing for RSI/ADX/ATR) per the
brief — *not* hand-ported — to keep this port small and auditable.

Parity covered by tests/test_bbtc_parity.py against a JSON baseline
generated by `npm run kairos:baseline`. If a future pandas-ta upgrade
changes initialization behavior, the parity test will catch it before
live trades diverge from backtest expectations.
"""
from typing import List, Optional, Dict
import math
import numpy as np
import pandas as pd

try:
    import pandas_ta as ta  # type: ignore
except Exception:  # pragma: no cover — environment without pandas-ta
    ta = None  # type: ignore


# ─── Indicator periods (must match shared/indicators/constants.ts) ─────────────
RSI_PERIOD = 14
ADX_PERIOD = 14
ATR_PERIOD = 14
EMA_FAST = 9
EMA_MID = 21
EMA_SLOW = 50
SMA_TREND = 200

# ─── BBTC-specific tunables (must match bbtc.ts) ───────────────────────────────
ATR_STOP_MULT = 2.5
ATR_TRAIL_MULT = 3.0
MIN_ADX_FOR_ENTRY = 20
RSI_CEILING_LONG = 65
RSI_CEILING_LONG_RISING = 75
RSI_FLOOR_SHORT = 35
RSI_FLOOR_SHORT_FALLING = 25
SMA200_SLOPE_LOOKBACK = 20


def _nan_arr(n: int) -> List[float]:
    return [float("nan")] * n


def _isnan(x) -> bool:
    return x is None or x != x


def compute_indicators(highs: List[float], lows: List[float], closes: List[float]) -> Dict[str, List[float]]:
    """Compute the indicator stack BBTC needs. Returns parallel lists aligned to closes.

    Uses pandas-ta for RSI/ADX/ATR (Wilder) and pandas EMA/SMA helpers.
    """
    if ta is None:
        raise RuntimeError("pandas-ta is required for BBTC indicator math")

    df = pd.DataFrame({"high": highs, "low": lows, "close": closes})
    ema9 = ta.ema(df["close"], length=EMA_FAST).tolist()
    ema21 = ta.ema(df["close"], length=EMA_MID).tolist()
    ema50 = ta.ema(df["close"], length=EMA_SLOW).tolist()
    sma200 = ta.sma(df["close"], length=SMA_TREND).tolist()
    atr14 = ta.atr(df["high"], df["low"], df["close"], length=ATR_PERIOD).tolist()
    rsi14 = ta.rsi(df["close"], length=RSI_PERIOD).tolist()
    adx_df = ta.adx(df["high"], df["low"], df["close"], length=ADX_PERIOD)
    # pandas-ta returns ADX_14 column name; fall back gracefully on version drift
    adx_col = f"ADX_{ADX_PERIOD}"
    if adx_df is None or adx_col not in adx_df.columns:
        adx14 = _nan_arr(len(closes))
    else:
        adx14 = adx_df[adx_col].tolist()

    return {
        "ema9": ema9,
        "ema21": ema21,
        "ema50": ema50,
        "sma200": sma200,
        "atr14": atr14,
        "rsi14": rsi14,
        "adx14": adx14,
    }


def compute_bbtc(
    closes: List[float],
    highs: List[float],
    lows: List[float],
    ema9: List[float],
    ema21: List[float],
    ema50: List[float],
    atr14: List[float],
    adx14: Optional[List[float]] = None,
    rsi14: Optional[List[float]] = None,
    sma200: Optional[List[float]] = None,
) -> dict:
    """Port of computeBBTC from bbtc.ts. Returns the same shape as BBTCResult.

    Caller may pass pre-computed indicators (e.g. from compute_indicators) to
    keep parity-test inputs deterministic. When indicators are omitted, we
    compute them via pandas-ta — match-or-fail is then up to parity tests.
    """
    n = len(closes)
    if adx14 is None or rsi14 is None or sma200 is None:
        ind = compute_indicators(highs, lows, closes)
        if adx14 is None:
            adx14 = ind["adx14"]
        if rsi14 is None:
            rsi14 = ind["rsi14"]
        if sma200 is None:
            sma200 = ind["sma200"]

    signals: List[Optional[str]] = [None] * n
    signal_sides: List[Optional[str]] = [None] * n

    in_position = False
    position_side: Optional[str] = None
    entry_price = 0.0
    entry_atr = 0.0
    highest_since_entry = 0.0
    lowest_since_entry = math.inf
    short_condition_prev = False

    for i in range(1, n):
        if _isnan(ema9[i]) or _isnan(ema21[i]) or _isnan(ema50[i]) or _isnan(atr14[i]):
            continue

        trend_strong = not _isnan(adx14[i]) and adx14[i] >= MIN_ADX_FOR_ENTRY

        sma_now = sma200[i]
        sma_past = sma200[i - SMA200_SLOPE_LOOKBACK] if i >= SMA200_SLOPE_LOOKBACK else float("nan")
        sma_rising = not _isnan(sma_past) and not _isnan(sma_now) and sma_now > sma_past
        sma_falling = not _isnan(sma_past) and not _isnan(sma_now) and sma_now < sma_past
        long_regime_ok = True if _isnan(sma_now) else (closes[i] > sma_now or sma_rising)
        short_regime_ok = True if _isnan(sma_now) else (closes[i] < sma_now or sma_falling)

        rsi_turning_up = (
            i >= 2
            and not _isnan(rsi14[i]) and not _isnan(rsi14[i - 1]) and not _isnan(rsi14[i - 2])
            and rsi14[i] > rsi14[i - 1] and rsi14[i - 1] > rsi14[i - 2]
        )
        rsi_turning_down = (
            i >= 2
            and not _isnan(rsi14[i]) and not _isnan(rsi14[i - 1]) and not _isnan(rsi14[i - 2])
            and rsi14[i] < rsi14[i - 1] and rsi14[i - 1] < rsi14[i - 2]
        )
        long_rsi_ok = (
            True if _isnan(rsi14[i])
            else (rsi14[i] < RSI_CEILING_LONG)
                 or (rsi14[i] < RSI_CEILING_LONG_RISING and rsi_turning_up)
        )
        short_rsi_ok = (
            True if _isnan(rsi14[i])
            else (rsi14[i] > RSI_FLOOR_SHORT)
                 or (rsi14[i] > RSI_FLOOR_SHORT_FALLING and rsi_turning_down)
        )

        long_stack_ok = ema9[i] > ema21[i] and closes[i] > ema50[i]
        short_stack_ok = ema9[i] < ema21[i] and closes[i] < ema50[i]

        short_conditions_now = short_stack_ok and trend_strong and short_regime_ok and short_rsi_ok
        short_rising_edge = short_conditions_now and not short_condition_prev

        if not in_position:
            # Long-only entry (shorts demoted to info-only — see TS reference).
            if long_stack_ok and trend_strong and long_regime_ok and long_rsi_ok:
                signals[i] = "BUY"
                signal_sides[i] = "LONG"
                in_position = True
                position_side = "LONG"
                entry_price = closes[i]
                entry_atr = atr14[i]
                highest_since_entry = highs[i]
                lowest_since_entry = lows[i]
        elif position_side == "LONG":
            highest_since_entry = max(highest_since_entry, highs[i])
            hard_stop = entry_price - entry_atr * ATR_STOP_MULT
            trail_stop = highest_since_entry - atr14[i] * ATR_TRAIL_MULT
            effective_stop = max(hard_stop, trail_stop)

            if lows[i] <= effective_stop:
                signals[i] = "STOP_HIT"
                signal_sides[i] = "LONG"
                in_position = False
                position_side = None
            elif ema9[i] < ema21[i] and closes[i] < ema50[i]:
                signals[i] = "SELL"
                signal_sides[i] = "LONG"
                in_position = False
                position_side = None

        # Info-only short edge emission
        if (not in_position) and signals[i] is None and short_rising_edge:
            signals[i] = "SELL"
            signal_sides[i] = "SHORT"
        short_condition_prev = short_conditions_now

    # Summarize last for the UI
    last_signal: Optional[str] = None
    last_signal_side: Optional[str] = None
    for i in range(n - 1, -1, -1):
        if signals[i]:
            last_signal = signals[i]
            last_signal_side = signal_sides[i]
            break

    top_signal = "HOLD"
    if (last_signal == "BUY" and last_signal_side == "LONG") or last_signal == "ADD_LONG":
        top_signal = "ENTER"
    elif (
        (last_signal == "SELL" and last_signal_side == "LONG")
        or (last_signal == "STOP_HIT" and last_signal_side == "LONG")
        or last_signal == "REDUCE"
    ):
        top_signal = "SELL"

    last_idx = n - 1
    stack_ready = not _isnan(ema9[last_idx]) and not _isnan(ema21[last_idx]) and not _isnan(ema50[last_idx])
    if stack_ready and ema9[last_idx] > ema21[last_idx] and closes[last_idx] > ema50[last_idx]:
        trend = "UP"; bias = "LONG"
    elif stack_ready and ema9[last_idx] < ema21[last_idx] and closes[last_idx] < ema50[last_idx]:
        trend = "DOWN"; bias = "SHORT"
    else:
        trend = "SIDEWAYS"; bias = "FLAT"

    return {
        "signals": signals,
        "signalSides": signal_sides,
        "lastSignal": last_signal,
        "topSignal": top_signal,
        "trend": trend,
        "bias": bias,
        "entryPrice": entry_price,
        "highestSinceEntry": highest_since_entry,
    }
