"""
HTF — High Tight Flag detector (Givens-loosened variant).

1:1 Python port of `server/signals/strategies/htf.ts`. TypeScript file is
the spec; any divergence is a bug. Parity covered by tests/test_htf_parity.py
against a JSON baseline generated by `npm run kairos:baseline`.

Setup rules:
  1. Pole — 30%+ price rise in 5–60 days
  2. Flag — 3–30 day consolidation with ≤25% pullback from pole high
  3. Breakout — close above flag high on volume ≥1.0× 30-day average
"""
from dataclasses import dataclass, asdict
from datetime import datetime
from math import isfinite
from typing import List, Optional, Tuple


# ─── Identification thresholds (must match htf.ts) ─────────────────────────────
POLE_MIN_GAIN = 0.3
POLE_MAX_DAYS = 60
POLE_MIN_DAYS = 5
FLAG_MIN_DAYS = 3
FLAG_MAX_DAYS = 30
FLAG_MAX_PULLBACK = 0.25
BREAKOUT_PAD = 0.001
MIN_BREAKOUT_VOL_RATIO = 1.0
HTF_VOL_AVG_WINDOW = 30
OVERHEAD_RESISTANCE_PCT = 0.10
OVERHEAD_RESISTANCE_LOOKBACK_BARS = 252


@dataclass
class HtfExtras:
    poleStartPrice: float
    poleEndPrice: float
    poleGainPct: float
    poleDays: int
    flagDays: int
    flagHigh: float
    flagLow: float
    flagPullbackPct: float
    breakoutVolRatio: float
    hasOverheadResistance: bool
    nearestResistancePct: Optional[float]


@dataclass
class HtfHit:
    symbol: str
    pattern: str  # "HTF_Givens" or "HTF_Givens_Forming"
    direction: str  # "long"
    breakoutDate: str  # ISO 8601
    breakoutPrice: float
    targetPrice: float
    stopPrice: float
    qualityScore: int
    patternStart: str
    patternEnd: str
    extras: HtfExtras

    def to_dict(self) -> dict:
        d = asdict(self)
        return d


def _rolling_vol_avg(volumes: List[float], window: int) -> List[float]:
    """Rolling N-bar average; NaN until window has min_periods samples.

    Matches the TS rollingVolAvg: min_periods = max(5, floor(window/3)).
    """
    n = len(volumes)
    out: List[float] = [float("nan")] * n
    min_periods = max(5, window // 3)
    s = 0.0
    for i, v in enumerate(volumes):
        s += v
        if i >= window:
            s -= volumes[i - window]
        count = min(i + 1, window)
        if count >= min_periods:
            out[i] = s / count
    return out


def _clamp_score(s: float) -> int:
    return max(0, min(100, round(s)))


def _to_iso(d) -> str:
    if isinstance(d, str):
        return d
    if isinstance(d, datetime):
        return d.isoformat()
    return str(d)


def _detect_overhead_resistance(
    highs: List[float],
    from_idx: int,
    ref_price: float,
    lookback_bars: int = OVERHEAD_RESISTANCE_LOOKBACK_BARS,
    within_pct: float = OVERHEAD_RESISTANCE_PCT,
) -> Tuple[bool, Optional[float]]:
    PEAK_K = 3
    ceiling = ref_price * (1 + within_pct)
    start_idx = max(PEAK_K, from_idx - lookback_bars)
    nearest_pct: Optional[float] = None
    for k in range(start_idx, from_idx - PEAK_K):
        h = highs[k]
        if h <= ref_price or h > ceiling:
            continue
        is_peak = True
        for j in range(1, PEAK_K + 1):
            if highs[k - j] >= h or highs[k + j] >= h:
                is_peak = False
                break
        if not is_peak:
            continue
        pct = (h - ref_price) / ref_price
        if nearest_pct is None or pct < nearest_pct:
            nearest_pct = pct
    return (nearest_pct is not None), nearest_pct


def _normalize_bars(bars: List[dict]) -> Tuple[List[float], List[float], List[float], List[float], List]:
    """Accept either {t,o,h,l,c,v} (TS shape) or {date,open,high,low,close,volume} (FMP shape).

    Returns (highs, lows, closes, vols, timestamps).
    """
    highs, lows, closes, vols, ts = [], [], [], [], []
    for b in bars:
        if "h" in b:
            highs.append(float(b["h"]))
            lows.append(float(b["l"]))
            closes.append(float(b["c"]))
            vols.append(float(b["v"]))
            ts.append(b.get("t"))
        else:
            highs.append(float(b["high"]))
            lows.append(float(b["low"]))
            closes.append(float(b["close"]))
            vols.append(float(b["volume"]))
            ts.append(b.get("date"))
    return highs, lows, closes, vols, ts


def scan_htf(
    bars: List[dict],
    symbol: str = "",
    lookback_days: int = 252,
    require_breakout: bool = True,
    min_score: int = 0,
) -> List[dict]:
    """Scan an OHLCV series for HTF setups. Returns hit dicts newest-first."""
    min_bars = POLE_MAX_DAYS + FLAG_MAX_DAYS + 5
    if len(bars) < min_bars:
        return []

    slice_from = max(0, len(bars) - (lookback_days + POLE_MAX_DAYS + FLAG_MAX_DAYS))
    df = bars[slice_from:]
    highs, lows, closes, vols, ts = _normalize_bars(df)
    vol_avg = _rolling_vol_avg(vols, HTF_VOL_AVG_WINDOW)

    hits: List[dict] = []
    last_idx = -999

    for i in range(POLE_MAX_DAYS + FLAG_MAX_DAYS, len(df)):
        best_flag_high: Optional[float] = None
        best_flag_low = 0.0
        best_flag_days = 0
        best_flag_start = 0

        for flag_days in range(FLAG_MIN_DAYS, FLAG_MAX_DAYS + 1):
            flag_start = i - flag_days
            if flag_start < POLE_MIN_DAYS:
                continue
            fh = float("-inf")
            fl = float("inf")
            for k in range(flag_start, i):
                if highs[k] > fh:
                    fh = highs[k]
                if lows[k] < fl:
                    fl = lows[k]
            if fh <= 0 or fl <= 0 or not isfinite(fh) or not isfinite(fl):
                continue
            pullback = (fh - fl) / fh
            if pullback > FLAG_MAX_PULLBACK:
                continue
            if flag_days > best_flag_days:
                best_flag_days = flag_days
                best_flag_high = fh
                best_flag_low = fl
                best_flag_start = flag_start

        if best_flag_high is None:
            continue

        flag_high_idx = best_flag_start
        pole_search_start = max(0, flag_high_idx - POLE_MAX_DAYS)
        pole_low_idx = pole_search_start
        pole_low = lows[pole_search_start]
        for k in range(pole_search_start + 1, flag_high_idx + 1):
            if lows[k] < pole_low:
                pole_low = lows[k]
                pole_low_idx = k
        if flag_high_idx - pole_search_start + 1 < POLE_MIN_DAYS:
            continue
        pole_days = flag_high_idx - pole_low_idx
        if pole_days < POLE_MIN_DAYS or pole_days > POLE_MAX_DAYS:
            continue
        pole_gain = (best_flag_high - pole_low) / pole_low if pole_low > 0 else 0
        if pole_gain < POLE_MIN_GAIN:
            continue

        is_breakout = closes[i] > best_flag_high * (1 + BREAKOUT_PAD)
        if not is_breakout and require_breakout:
            continue

        va = vol_avg[i]
        vol_ratio = (vols[i] / va) if (va and not (va != va)) else 0  # NaN check via self-compare
        if is_breakout and vol_ratio < MIN_BREAKOUT_VOL_RATIO and require_breakout:
            continue

        if i - last_idx < FLAG_MIN_DAYS:
            continue

        target = closes[i] + 0.5 * (best_flag_high - pole_low)
        stop = best_flag_low * 0.98

        score = 50
        if pole_gain >= 1.0:
            score += 15
        elif pole_gain >= 0.6:
            score += 10
        elif pole_gain >= 0.3:
            score += 5
        if best_flag_days >= 10:
            score += 10
        elif best_flag_days >= 5:
            score += 5
        pullback_pct = (best_flag_high - best_flag_low) / best_flag_high
        if pullback_pct <= 0.1:
            score += 10
        elif pullback_pct <= 0.15:
            score += 5
        if vol_ratio >= 2.0:
            score += 15
        elif vol_ratio >= 1.5:
            score += 10
        elif vol_ratio >= 1.3:
            score += 5

        final_score = _clamp_score(score)
        if final_score < min_score:
            continue

        has_resistance, nearest_pct = _detect_overhead_resistance(highs, i, closes[i])

        hits.append({
            "symbol": symbol,
            "pattern": "HTF_Givens",
            "direction": "long",
            "breakoutDate": _to_iso(ts[i]),
            "breakoutPrice": closes[i],
            "targetPrice": target,
            "stopPrice": stop,
            "qualityScore": final_score,
            "patternStart": _to_iso(ts[pole_low_idx]),
            "patternEnd": _to_iso(ts[i]),
            "extras": {
                "poleStartPrice": pole_low,
                "poleEndPrice": best_flag_high,
                "poleGainPct": pole_gain * 100,
                "poleDays": pole_days,
                "flagDays": best_flag_days,
                "flagHigh": best_flag_high,
                "flagLow": best_flag_low,
                "flagPullbackPct": pullback_pct * 100,
                "breakoutVolRatio": vol_ratio,
                "hasOverheadResistance": has_resistance,
                "nearestResistancePct": round(nearest_pct * 100, 2) if nearest_pct is not None else None,
            },
        })
        last_idx = i

    hits.sort(key=lambda h: h["breakoutDate"], reverse=True)
    return hits


def scan_forming_htf(bars: List[dict], symbol: str = "") -> Optional[dict]:
    """Detect a pattern still FORMING — pole + flag valid right now, no breakout yet.

    Returns one hypothetical hit (entry = flag_high × (1+BREAKOUT_PAD)) or None.
    """
    if len(bars) < POLE_MAX_DAYS + FLAG_MAX_DAYS + 5:
        return None

    highs, lows, closes, vols, ts = _normalize_bars(bars)
    n = len(closes)
    vol_avg = _rolling_vol_avg(vols, HTF_VOL_AVG_WINDOW)

    best_flag_high: Optional[float] = None
    best_flag_low = 0.0
    best_flag_days = 0
    best_flag_start = 0

    for flag_days in range(FLAG_MIN_DAYS, FLAG_MAX_DAYS + 1):
        flag_start = n - flag_days
        if flag_start < POLE_MIN_DAYS:
            continue
        fh = float("-inf")
        fl = float("inf")
        for k in range(flag_start, n):
            if highs[k] > fh:
                fh = highs[k]
            if lows[k] < fl:
                fl = lows[k]
        if not isfinite(fh) or not isfinite(fl) or fh <= 0 or fl <= 0:
            continue
        pullback = (fh - fl) / fh
        if pullback > FLAG_MAX_PULLBACK:
            continue
        if flag_days > best_flag_days:
            best_flag_days = flag_days
            best_flag_high = fh
            best_flag_low = fl
            best_flag_start = flag_start

    if best_flag_high is None:
        return None

    flag_high_idx = best_flag_start
    pole_search_start = max(0, flag_high_idx - POLE_MAX_DAYS)
    pole_low_idx = pole_search_start
    pole_low = lows[pole_search_start]
    for k in range(pole_search_start + 1, flag_high_idx + 1):
        if lows[k] < pole_low:
            pole_low = lows[k]
            pole_low_idx = k
    if flag_high_idx - pole_search_start + 1 < POLE_MIN_DAYS:
        return None
    pole_days = flag_high_idx - pole_low_idx
    if pole_days < POLE_MIN_DAYS or pole_days > POLE_MAX_DAYS:
        return None
    pole_gain = (best_flag_high - pole_low) / pole_low if pole_low > 0 else 0
    if pole_gain < POLE_MIN_GAIN:
        return None

    current_price = closes[n - 1]
    if current_price > best_flag_high * (1 + BREAKOUT_PAD):
        return None  # already fired
    if current_price < best_flag_low:
        return None  # already stopped

    trigger_price = best_flag_high * (1 + BREAKOUT_PAD)
    stop = best_flag_low * 0.98
    target = trigger_price + 0.5 * (best_flag_high - pole_low)
    pullback_pct = (best_flag_high - best_flag_low) / best_flag_high
    last_va = vol_avg[n - 1]
    last_vol_ratio = (vols[n - 1] / last_va) if (last_va and not (last_va != last_va)) else 0

    score = 50
    if pole_gain >= 1.0:
        score += 15
    elif pole_gain >= 0.6:
        score += 10
    elif pole_gain >= 0.3:
        score += 5
    if best_flag_days >= 10:
        score += 10
    elif best_flag_days >= 5:
        score += 5
    if pullback_pct <= 0.1:
        score += 10
    elif pullback_pct <= 0.15:
        score += 5

    has_resistance, nearest_pct = _detect_overhead_resistance(highs, n - 1, trigger_price)

    return {
        "symbol": symbol,
        "pattern": "HTF_Givens",
        "direction": "long",
        "breakoutDate": _to_iso(ts[n - 1]),
        "breakoutPrice": trigger_price,
        "targetPrice": target,
        "stopPrice": stop,
        "qualityScore": _clamp_score(score),
        "patternStart": _to_iso(ts[pole_low_idx]),
        "patternEnd": _to_iso(ts[n - 1]),
        "extras": {
            "poleStartPrice": pole_low,
            "poleEndPrice": best_flag_high,
            "poleGainPct": pole_gain * 100,
            "poleDays": pole_days,
            "flagDays": best_flag_days,
            "flagHigh": best_flag_high,
            "flagLow": best_flag_low,
            "flagPullbackPct": pullback_pct * 100,
            "breakoutVolRatio": last_vol_ratio,
            "hasOverheadResistance": has_resistance,
            "nearestResistancePct": round(nearest_pct * 100, 2) if nearest_pct is not None else None,
        },
    }
