/**
 * KAIROS parity-baseline generator.
 *
 * Synthesizes deterministic OHLCV bars (seeded LCG), runs scanHtf() and
 * computeBBTC() against them, and emits both the inputs and outputs as
 * JSON into python/kairos/tests/baseline/. The Python parity tests
 * (tests/test_htf_parity.py, tests/test_bbtc_parity.py) read those files
 * and assert that the Python ports produce identical results.
 *
 * Re-run with: `npm run kairos:baseline` whenever scanHtf or computeBBTC
 * change. Commit the regenerated JSON.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { scanHtf } from "../server/signals/strategies/htf";
import { computeBBTC } from "../server/signals/strategies/bbtc";
import type { OHLCV } from "../server/data/types";

const __dirname = dirname(fileURLToPath(import.meta.url));
const BASELINE_DIR = resolve(__dirname, "../python/kairos/tests/baseline");
mkdirSync(BASELINE_DIR, { recursive: true });

// ─── Seeded LCG for cross-language reproducibility ────────────────────────────
function lcg(seed: number) {
  let s = seed >>> 0;
  return () => {
    s = (Math.imul(s, 1664525) + 1013904223) >>> 0;
    return s / 0x100000000;
  };
}

// ─── Bar synthesizer with an embedded HTF setup ───────────────────────────────
function synthBars(): { isoDate: string; t: Date; o: number; h: number; l: number; c: number; v: number }[] {
  const rng = lcg(42);
  const bars: { isoDate: string; t: Date; o: number; h: number; l: number; c: number; v: number }[] = [];
  const start = new Date(Date.UTC(2024, 0, 2));
  let price = 50;
  for (let i = 0; i < 260; i++) {
    let drift = 0.0005;
    let vol = 0.012;
    let volume = 1_000_000;
    // Pole: bars 150–195 climb ~1.2% / day → ~70% gain
    if (i >= 150 && i < 195) {
      drift = 0.0115;
      vol = 0.014;
      volume = 1_400_000;
    }
    // Flag: bars 195–214 tight consolidation
    if (i >= 195 && i < 214) {
      drift = 0;
      vol = 0.005;
      volume = 900_000;
    }
    // Breakout bar: 214 on heavy volume
    if (i === 214) {
      drift = 0.055;
      vol = 0.01;
      volume = 3_200_000;
    }
    // Post-breakout drift up for BBTC
    if (i >= 215) {
      drift = 0.004;
      vol = 0.012;
      volume = 1_200_000;
    }
    const ret = drift + (rng() - 0.5) * vol;
    const open = price;
    const close = open * (1 + ret);
    const high = Math.max(open, close) * (1 + Math.abs((rng() - 0.5) * 0.006));
    const low = Math.min(open, close) * (1 - Math.abs((rng() - 0.5) * 0.006));
    const d = new Date(start.getTime() + i * 86400000);
    bars.push({
      isoDate: d.toISOString().slice(0, 10),
      t: d,
      o: Number(open.toFixed(4)),
      h: Number(high.toFixed(4)),
      l: Number(low.toFixed(4)),
      c: Number(close.toFixed(4)),
      v: volume,
    });
    price = close;
  }
  return bars;
}

// ─── Indicator helpers BBTC requires (verbatim from bbtc-parity.ts) ───────────
function computeEMA(closes: number[], length: number): number[] {
  const ema: number[] = new Array(closes.length).fill(NaN);
  const k = 2 / (length + 1);
  let sum = 0;
  for (let i = 0; i < length && i < closes.length; i++) sum += closes[i];
  if (closes.length >= length) {
    ema[length - 1] = sum / length;
    for (let i = length; i < closes.length; i++) {
      ema[i] = closes[i] * k + ema[i - 1] * (1 - k);
    }
  }
  return ema;
}

function computeATR(highs: number[], lows: number[], closes: number[], period: number): number[] {
  const atr: number[] = new Array(closes.length).fill(NaN);
  const tr: number[] = new Array(closes.length).fill(0);
  tr[0] = highs[0] - lows[0];
  for (let i = 1; i < closes.length; i++) {
    tr[i] = Math.max(
      highs[i] - lows[i],
      Math.abs(highs[i] - closes[i - 1]),
      Math.abs(lows[i] - closes[i - 1])
    );
  }
  let sum = 0;
  for (let i = 0; i < period && i < tr.length; i++) sum += tr[i];
  if (tr.length >= period) {
    atr[period - 1] = sum / period;
    for (let i = period; i < tr.length; i++) {
      atr[i] = (atr[i - 1] * (period - 1) + tr[i]) / period;
    }
  }
  return atr;
}

// ─── Run ──────────────────────────────────────────────────────────────────────
const synth = synthBars();
const ohlcvForHtf: OHLCV[] = synth.map(b => ({ t: b.t, o: b.o, h: b.h, l: b.l, c: b.c, v: b.v }));

// HTF baseline ----------------------------------------------------------------
const hits = scanHtf(ohlcvForHtf, "SYNTH");

const htfPayload = {
  comment: "Generated by scripts/kairos-baseline.ts — do not hand-edit. Regenerate with `npm run kairos:baseline`.",
  symbol: "SYNTH",
  bars: synth.map(b => ({
    date: b.isoDate,
    open: b.o, high: b.h, low: b.l, close: b.c, volume: b.v,
  })),
  hits: hits.map(h => ({
    ...h,
    breakoutDate: h.breakoutDate instanceof Date ? h.breakoutDate.toISOString() : h.breakoutDate,
    patternStart: h.patternStart instanceof Date ? h.patternStart.toISOString() : h.patternStart,
    patternEnd: h.patternEnd instanceof Date ? h.patternEnd.toISOString() : h.patternEnd,
  })),
};
writeFileSync(resolve(BASELINE_DIR, "htf_baseline.json"), JSON.stringify(htfPayload, null, 2));
console.log(`HTF baseline: ${hits.length} hit(s) on ${synth.length} bars`);

// BBTC baseline ---------------------------------------------------------------
const closes = synth.map(b => b.c);
const highs = synth.map(b => b.h);
const lows = synth.map(b => b.l);
const ema9 = computeEMA(closes, 9);
const ema21 = computeEMA(closes, 21);
const ema50 = computeEMA(closes, 50);
const atr14 = computeATR(highs, lows, closes, 14);
const bb = computeBBTC({ closes, highs, lows, ema9, ema21, ema50, atr14 });

const bbtcPayload = {
  comment: "Generated by scripts/kairos-baseline.ts. Inputs include the pre-computed EMA9/21/50 and ATR14 that the TS implementation used — the Python parity test feeds the SAME indicator inputs so the parity check measures only the strategy logic, not pandas-ta vs hand-rolled indicator drift.",
  symbol: "SYNTH",
  bars: synth.map(b => ({
    date: b.isoDate,
    open: b.o, high: b.h, low: b.l, close: b.c, volume: b.v,
  })),
  indicators: { ema9, ema21, ema50, atr14 },
  result: {
    signals: bb.signals,
    signalSides: bb.signalSides,
    lastSignal: bb.lastSignal,
    topSignal: bb.topSignal,
    trend: bb.trend,
    bias: bb.bias,
    entryPrice: bb.entryPrice,
    highestSinceEntry: bb.highestSinceEntry,
  },
};
writeFileSync(resolve(BASELINE_DIR, "bbtc_baseline.json"), JSON.stringify(bbtcPayload, null, 2));
const sigCount = bb.signals.filter(s => s !== null).length;
console.log(`BBTC baseline: ${sigCount} signal(s), top=${bb.topSignal}, trend=${bb.trend}`);

console.log(`\nWrote baselines to ${BASELINE_DIR}`);
